{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://analyticsreporting.googleapis.com/"
    }
  ],
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "description": "Accesses Analytics report data.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Analytics Reporting",
    "version": "v4",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/lucybot/api-spec-converter",
          "version": "2.7.31"
        },
        "format": "google",
        "url": "https://analyticsreporting.googleapis.com/$discovery/rest?version=v4",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "analyticsreporting"
  },
  "tags": [
    {
      "name": "reports"
    },
    {
      "name": "userActivity"
    }
  ],
  "paths": {
    "/v4/reports:batchGet": {
      "post": {
        "description": "Returns the Analytics data.",
        "operationId": "analyticsreporting.reports.batchGet",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/analytics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "reports"
        ]
      }
    },
    "/v4/userActivity:search": {
      "post": {
        "description": "Returns User Activity data.",
        "operationId": "analyticsreporting.userActivity.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/analytics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "userActivity"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "description": "Oauth 2.0 implicit authentication",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/analytics": "View and manage your Google Analytics data",
              "https://www.googleapis.com/auth/analytics.readonly": "View your Google Analytics data"
            }
          }
        },
        "type": "oauth2"
      },
      "Oauth2c": {
        "description": "Oauth 2.0 accessCode authentication",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/analytics": "View and manage your Google Analytics data",
              "https://www.googleapis.com/auth/analytics.readonly": "View your Google Analytics data"
            },
            "tokenUrl": "https://accounts.google.com/o/oauth2/token"
          }
        },
        "type": "oauth2"
      }
    }
  }
}